/* Copyright 2015-2016 CyberTech Labs Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was modified by Mikhail Wall to make it comply with the requirements of trikRuntime
 * project. See git revision history for detailed changes. */

#pragma once

#include <QtWidgets/QDialog>
#include <QtWidgets/QPushButton>
#include <QtNetwork/QTcpSocket>

namespace Ui {
class ConnectForm;
}

class ConnectForm : public QDialog
{
	Q_OBJECT

public:
	ConnectForm(QTcpSocket *socket, QWidget *parent = 0);
	~ConnectForm();

private slots:

	/// Slot for button for connecting to robot
	void on_connectButton_clicked();

	/// Slot for ok button
	void on_buttonBox_accepted();

	/// Slot for cancel button
	void on_buttonBox_rejected();

private:

	/// Field with GUI automatically generated by connectForm.ui.
	Ui::ConnectForm *mUi;

	/// Connect button
	QPushButton *mConnectButton;

	/// QTcpSockets for saving state of internet connection
	QTcpSocket *mSocket;
	QTcpSocket *mSocket_;

};

